### ISSUE TITLE
Accessibility - change "here" to more descriptive link

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/shinySPC#2]
Following the thread https://twitter.com/Em1lySm/status/1516741011422199810 it's advisable to not just use "here" as a link for accessibility.

https://github.com/nhs-r-community/shinySPC/blob/a79867da9ff082c94d3851ac36097f2212a1fcb1/README.md

**Comment by helenajr** [comment]
Don't think the link works anymore? Link somewhere else?

**Comment by Lextuga007** [comment]
Good point! It was linking to a Shiny server that's changed but the issue was originally to help move away from using language like:

"The link can be found [here](https://involve.nottshc.nhs.uk/rsconnect/content/879e1268-8e24-4d8e-98c5-1786a876d825/)" 

to something more readable like:

The [shiny app](https://involve.nottshc.nhs.uk/rsconnect/content/879e1268-8e24-4d8e-98c5-1786a876d825/) example is hosted on a Shiny server in Nottinghamshire Healthcare Trust"

This is quite an old repository so we might need to archive it. It'll still be available but not so prominent in the repository list.
